name: GitHub Actions CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uv
        run: pip install uv

      - name: Install dependencies (with dev)
        run: uv sync --all-extras

      - name: Run linter (ruff)
        run: uv run ruff check gendiff tests

      - name: Run tests
        run: uv run pytest --maxfail=1 --disable-warnings -v

      - name: Run tests with coverage
        run: uv run pytest --cov=gendiff --cov-report xml

      - name: Debug coverage paths
        run: |
          echo "Первые строки coverage.xml:"
          head -n 20 coverage.xml
          echo ""
          echo "Файл coverage.xml в каталоге:"
          ls -la coverage.xml

      - name: Upload coverage to SonarCloud
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONARQUBE }}
        
